sudo: required
services:
 - docker

before_install:
 - docker build -t gautamsarup/docker-react -f Dockerfile.dev .

script:
 - docker run gautamsarup/docker-react npm run test -- --coverage

deploy:
 provider:elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-1-783074804886"
 bucker_path: "docker-react"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key:
  secure: "AWS_SECRET_KEY"